# Generated by Django 5.2.5 on 2025-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_delete_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_leaf',
            field=models.BooleanField(default=True),
        ),
    ]
