# Generated by Django 5.2.5 on 2025-08-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_is_leaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='childrens',
            field=models.ManyToManyField(blank=True, to='menu.menuitem'),
        ),
    ]
