# Generated by Django 5.2.5 on 2025-08-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_childrens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='childrens',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='childrens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
