# Generated by Django 5.2.5 on 2025-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menuitem_childrens_menuitem_childrens'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='child',
            field=models.ManyToManyField(blank=True, to='menu.menuitem'),
        ),
    ]
