# Generated by Django 5.2.5 on 2025-08-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='child',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='childrens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par', to='menu.menuitem'),
        ),
    ]
