# Generated by Django 5.2.5 on 2025-08-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_menuitem_child_alter_menuitem_childrens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='childrens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='menu.menuitem'),
        ),
    ]
