# Generated by Django 5.2.5 on 2025-08-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuitem_childrens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='childrens',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_leaf',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
